services:
  app:
    build: ./app
    command: ./docker-entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery_beat:
    build: ./app
    command: sh -c "rm -f './celerybeat.pid' && celery -A lunch_voter beat -l INFO"
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lunch_voter
      - POSTGRES_PASSWORD=lunch_voter
      - POSTGRES_DB=lunch_voter_dev_db

volumes:
  postgres_data: